export interface BookingRevenueInput {
  check_in: string;
  check_out: string;
  total_amount: number | string | null;
}

/**
 * Returns the number of nights for a booking.
 *
 * Example:
 * check-in  : 2026-08-01
 * check-out : 2026-08-09
 * nights    : 8
 */
export function getBookingNights(
  checkIn: string,
  checkOut: string
): number {
  if (!checkIn || !checkOut) {
    return 0;
  }

  const start = new Date(`${checkIn}T00:00:00`);
  const end = new Date(`${checkOut}T00:00:00`);

  const difference =
    end.getTime() - start.getTime();

  const nights = Math.ceil(
    difference / (1000 * 60 * 60 * 24)
  );

  return Math.max(0, nights);
}

/**
 * Returns the total amount allocated to one night.
 *
 * Example:
 * Total booking = ₹9,000
 * Nights = 8
 *
 * Result = ₹1,125
 */
export function getBookingPerNightAmount(
  booking: BookingRevenueInput
): number {
  const totalAmount =
    Number(booking.total_amount || 0);

  const nights = getBookingNights(
    booking.check_in,
    booking.check_out
  );

  if (nights <= 0) {
    return 0;
  }

  return totalAmount / nights;
}

/**
 * Returns the revenue generated by a booking
 * for a specific date.
 *
 * The booking earns revenue for each night
 * from check-in date up to, but NOT including,
 * the check-out date.
 *
 * Example:
 *
 * Check-in  : Aug 1
 * Check-out : Aug 4
 * Total     : ₹3,000
 *
 * Aug 1 → ₹1,000
 * Aug 2 → ₹1,000
 * Aug 3 → ₹1,000
 * Aug 4 → ₹0
 */
export function getBookingRevenueForDate(
  booking: BookingRevenueInput,
  date: string
): number {
  if (!booking.check_in || !booking.check_out) {
    return 0;
  }

  if (!date) {
    return 0;
  }

  const checkIn = booking.check_in;
  const checkOut = booking.check_out;

  /*
   * Check-out day does not generate a night's revenue.
   */
  if (date < checkIn || date >= checkOut) {
    return 0;
  }

  return getBookingPerNightAmount(
    booking
  );
}

/**
 * Returns the total revenue generated by
 * a booking across a date range.
 *
 * This is useful for monthly reports.
 *
 * Example:
 *
 * Booking:
 * Aug 28 → Sep 3
 * Total = ₹6,000
 * Nights = 6
 *
 * August report:
 * Aug 28, 29, 30, 31
 * = 4 × ₹1,000
 * = ₹4,000
 *
 * September report:
 * Sep 1, 2
 * = 2 × ₹1,000
 * = ₹2,000
 */
export function getBookingRevenueForDateRange(
  booking: BookingRevenueInput,
  startDate: string,
  endDate: string
): number {
  if (!startDate || !endDate) {
    return 0;
  }

  const nights =
    getBookingNights(
      booking.check_in,
      booking.check_out
    );

  if (nights <= 0) {
    return 0;
  }

  const perNight =
    getBookingPerNightAmount(
      booking
    );

  let revenue = 0;

  const bookingStart =
    new Date(`${booking.check_in}T00:00:00`);

  const bookingEnd =
    new Date(`${booking.check_out}T00:00:00`);

  const rangeStart =
    new Date(`${startDate}T00:00:00`);

  const rangeEnd =
    new Date(`${endDate}T00:00:00`);

  /*
   * Move through each night of the booking.
   */
  const current = new Date(
    Math.max(
      bookingStart.getTime(),
      rangeStart.getTime()
    )
  );

  const finalDate = new Date(
    Math.min(
      bookingEnd.getTime(),
      rangeEnd.getTime()
    )
  );

  while (
    current.getTime() <
    finalDate.getTime()
  ) {
    revenue += perNight;

    current.setDate(
      current.getDate() + 1
    );
  }

  return revenue;
}